### ISSUE TITLE
Encountering "Something went wrong" screen on exit after tag export

### ISSUE THREAD

**Issue by just-a-garlic-bread** [OneFolderApp/OneFolder#10]
<b>Which actions did you perform before the error occurred?</b>
Bug happened multiple times, when i decided to export the tags  to the file's  metadata.
To note, he error message doesnt appear immediately, but does so only when i close the settings window.
It doesnt appear when i open and close the settings window without exporting tags.
(Might try to re-download the application, to see if error still persists)

<b>What did you expect to happen?</b>
Usually, when tag saving works out well, the times when it did happen, it showed a saving progress in percentages, instead of immediately saying that it is done(Probably related to it, but im not sure.)

<b>Stacktrace</b>
```
IPC method called after context was released
    at EventEmitter.send (node:electron/js2c/renderer_init:2:14057)
    at node:electron/js2c/renderer_init:2:32075
    at cleanup (webpack://onefolder/src/frontend/components/PopupWindow.tsx:50:21)
    at safelyCallDestroy (webpack://onefolder/node_modules/react-dom/cjs/react-dom.development.js:22932:0)
    at commitHookEffectListUnmount (webpack://onefolder/node_modules/react-dom/cjs/react-dom.development.js:23100:0)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (webpack://onefolder/node_modules/react-dom/cjs/react-dom.development.js:25101:0)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (webpack://onefolder/node_modules/react-dom/cjs/react-dom.development.js:25048:0)
    at commitPassiveUnmountEffects_begin (webpack://onefolder/node_modules/react-dom/cjs/react-dom.development.js:24956:0)
    at commitPassiveUnmountEffects (webpack://onefolder/node_modules/react-dom/cjs/react-dom.development.js:24941:0)
    at flushPassiveEffectsImpl (webpack://onefolder/node_modules/react-dom/cjs/react-dom.development.js:27038:0)
```

<b>Runtime info</b>
<ul>
<li>OneFolder version: v0.1.5</li>
<li>Operating system: Windows_NT 10.0.19044, win32 x64</li>
<li>Node version: v18.17.1</li>
</ul>

**Comment by just-a-garlic-bread** [comment]
Reinstalling the application helped.Im really sorry for making a rushed decision, it was a mistake on my end
