### ISSUE TITLE
ExifTool importation tags bug (IPTC/XMP)

### ISSUE THREAD

**Issue by Xavier-LB** [OneFolderApp/OneFolder#59]

**Comment by Xavier-LB** [comment]
`FileStore.ts:109 Could not import tags for /Users/xlb/onefolder/test-photos/folder1/P1036990.JPG Error: Warning: IPTCDigest is not current. XMP may be out of sync - /Users/xlb/onefolder/test-photos/folder1/P1036990.JPG
    at ExifIO.readTags (ExifIO.ts:127:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FileStore.readTagsFromFiles (FileStore.ts:82:39)
    at async LocationStore.initLocation (LocationStore.ts:430:7)`

**Comment by Xavier-LB** [comment]
ChatGPT explanation:
https://chat.openai.com/share/ff98e66f-5207-4475-9f8f-71d233a00cc2
